#!/bin/sh

DATAPATH=$SETUP_INSTALLPATH
CURPWD=$PWD

HIDDENDIR=".vegastrike.4.x"

cd $DATAPATH
echo $DATAPATH
rm -f $DATAPATH/$HIDDENDIR/*.m3u
mv $DATAPATH/$HIDDENDIR/midim3u/* $DATAPATH/$HIDDENDIR/
rmdir $DATAPATH/$HIDDENDIR/midim3u
