#!/bin/bash
svn mv textures/backgrounds/black_sphere.bmp textures/backgrounds/black_sphere.image
svn mv textures/backgrounds/blue2_back.bmp textures/backgrounds/blue2_back.image
svn mv textures/backgrounds/blue2_down.bmp textures/backgrounds/blue2_down.image
svn mv textures/backgrounds/blue2_front.bmp textures/backgrounds/blue2_front.image
svn mv textures/backgrounds/blue2_left.bmp textures/backgrounds/blue2_left.image
svn mv textures/backgrounds/blue2_right.bmp textures/backgrounds/blue2_right.image
svn mv textures/backgrounds/blue2_up.bmp textures/backgrounds/blue2_up.image
svn mv textures/backgrounds/blue_back.bmp textures/backgrounds/blue_back.image
svn mv textures/backgrounds/bluedazzle_back.bmp textures/backgrounds/bluedazzle_back.image
svn mv textures/backgrounds/bluedazzle_down.bmp textures/backgrounds/bluedazzle_down.image
svn mv textures/backgrounds/bluedazzle_front.bmp textures/backgrounds/bluedazzle_front.image
svn mv textures/backgrounds/bluedazzle_left.bmp textures/backgrounds/bluedazzle_left.image
svn mv textures/backgrounds/bluedazzle_right.bmp textures/backgrounds/bluedazzle_right.image
svn mv textures/backgrounds/bluedazzle_up.bmp textures/backgrounds/bluedazzle_up.image
svn mv textures/backgrounds/blue_down.bmp textures/backgrounds/blue_down.image
svn mv textures/backgrounds/blue_front.bmp textures/backgrounds/blue_front.image
svn mv textures/backgrounds/blue_galaxy1_back.bmp textures/backgrounds/blue_galaxy1_back.image
svn mv textures/backgrounds/blue_galaxy1_down.bmp textures/backgrounds/blue_galaxy1_down.image
svn mv textures/backgrounds/blue_galaxy1_front.bmp textures/backgrounds/blue_galaxy1_front.image
svn mv textures/backgrounds/blue_galaxy1_left.bmp textures/backgrounds/blue_galaxy1_left.image
svn mv textures/backgrounds/blue_galaxy1_right.bmp textures/backgrounds/blue_galaxy1_right.image
svn mv textures/backgrounds/blue_galaxy1_up.bmp textures/backgrounds/blue_galaxy1_up.image
svn mv textures/backgrounds/bluegreen_back.bmp textures/backgrounds/bluegreen_back.image
svn mv textures/backgrounds/bluegreen_down.bmp textures/backgrounds/bluegreen_down.image
svn mv textures/backgrounds/bluegreen_front.bmp textures/backgrounds/bluegreen_front.image
svn mv textures/backgrounds/bluegreen_left.bmp textures/backgrounds/bluegreen_left.image
svn mv textures/backgrounds/bluegreen_right.bmp textures/backgrounds/bluegreen_right.image
svn mv textures/backgrounds/bluegreen_up.bmp textures/backgrounds/bluegreen_up.image
svn mv textures/backgrounds/blue_left.bmp textures/backgrounds/blue_left.image
svn mv textures/backgrounds/blue_right.bmp textures/backgrounds/blue_right.image
svn mv textures/backgrounds/blue_up.bmp textures/backgrounds/blue_up.image
svn mv textures/backgrounds/darkgreen_back.bmp textures/backgrounds/darkgreen_back.image
svn mv textures/backgrounds/darkgreen_down.bmp textures/backgrounds/darkgreen_down.image
svn mv textures/backgrounds/darkgreen_front.bmp textures/backgrounds/darkgreen_front.image
svn mv textures/backgrounds/darkgreen_left.bmp textures/backgrounds/darkgreen_left.image
svn mv textures/backgrounds/darkgreen_right.bmp textures/backgrounds/darkgreen_right.image
svn mv textures/backgrounds/darkgreen_up.bmp textures/backgrounds/darkgreen_up.image
svn mv textures/backgrounds/emerald_back.bmp textures/backgrounds/emerald_back.image
svn mv textures/backgrounds/emerald_down.bmp textures/backgrounds/emerald_down.image
svn mv textures/backgrounds/emerald_front.bmp textures/backgrounds/emerald_front.image
svn mv textures/backgrounds/emerald_left.bmp textures/backgrounds/emerald_left.image
svn mv textures/backgrounds/emerald_right.bmp textures/backgrounds/emerald_right.image
svn mv textures/backgrounds/emerald_up.bmp textures/backgrounds/emerald_up.image
svn mv textures/backgrounds/fiery_galaxy_back.bmp textures/backgrounds/fiery_galaxy_back.image
svn mv textures/backgrounds/fiery_galaxy_down.bmp textures/backgrounds/fiery_galaxy_down.image
svn mv textures/backgrounds/fiery_galaxy_front.bmp textures/backgrounds/fiery_galaxy_front.image
svn mv textures/backgrounds/fiery_galaxy_left.bmp textures/backgrounds/fiery_galaxy_left.image
svn mv textures/backgrounds/fiery_galaxy_right.bmp textures/backgrounds/fiery_galaxy_right.image
svn mv textures/backgrounds/fiery_galaxy_up.bmp textures/backgrounds/fiery_galaxy_up.image
svn mv textures/backgrounds/green_back.bmp textures/backgrounds/green_back.image
svn mv textures/backgrounds/green_down.bmp textures/backgrounds/green_down.image
svn mv textures/backgrounds/green_front.bmp textures/backgrounds/green_front.image
svn mv textures/backgrounds/green_left.bmp textures/backgrounds/green_left.image
svn mv textures/backgrounds/green_right.bmp textures/backgrounds/green_right.image
svn mv textures/backgrounds/green_up.bmp textures/backgrounds/green_up.image
svn mv textures/backgrounds/lightgreen_back.bmp textures/backgrounds/lightgreen_back.image
svn mv textures/backgrounds/lightgreen_down.bmp textures/backgrounds/lightgreen_down.image
svn mv textures/backgrounds/lightgreen_front.bmp textures/backgrounds/lightgreen_front.image
svn mv textures/backgrounds/lightgreen_left.bmp textures/backgrounds/lightgreen_left.image
svn mv textures/backgrounds/lightgreen_right.bmp textures/backgrounds/lightgreen_right.image
svn mv textures/backgrounds/lightgreen_up.bmp textures/backgrounds/lightgreen_up.image
svn mv textures/backgrounds/magic_galaxy2_back.bmp textures/backgrounds/magic_galaxy2_back.image
svn mv textures/backgrounds/magic_galaxy2_down.bmp textures/backgrounds/magic_galaxy2_down.image
svn mv textures/backgrounds/magic_galaxy2_front.bmp textures/backgrounds/magic_galaxy2_front.image
svn mv textures/backgrounds/magic_galaxy2_left.bmp textures/backgrounds/magic_galaxy2_left.image
svn mv textures/backgrounds/magic_galaxy2_right.bmp textures/backgrounds/magic_galaxy2_right.image
svn mv textures/backgrounds/magic_galaxy2_up.bmp textures/backgrounds/magic_galaxy2_up.image
svn mv textures/backgrounds/magic_galaxy3_back.bmp textures/backgrounds/magic_galaxy3_back.image
svn mv textures/backgrounds/magic_galaxy3_down.bmp textures/backgrounds/magic_galaxy3_down.image
svn mv textures/backgrounds/magic_galaxy3_front.bmp textures/backgrounds/magic_galaxy3_front.image
svn mv textures/backgrounds/magic_galaxy3_left.bmp textures/backgrounds/magic_galaxy3_left.image
svn mv textures/backgrounds/magic_galaxy3_right.bmp textures/backgrounds/magic_galaxy3_right.image
svn mv textures/backgrounds/magic_galaxy3_up.bmp textures/backgrounds/magic_galaxy3_up.image
svn mv textures/backgrounds/magic_galaxy_back.bmp textures/backgrounds/magic_galaxy_back.image
svn mv textures/backgrounds/magic_galaxy_down.bmp textures/backgrounds/magic_galaxy_down.image
svn mv textures/backgrounds/magic_galaxy_front.bmp textures/backgrounds/magic_galaxy_front.image
svn mv textures/backgrounds/magic_galaxy_left.bmp textures/backgrounds/magic_galaxy_left.image
svn mv textures/backgrounds/magic_galaxy_right.bmp textures/backgrounds/magic_galaxy_right.image
svn mv textures/backgrounds/magic_galaxy_up.bmp textures/backgrounds/magic_galaxy_up.image
svn mv textures/backgrounds/mustard_back.bmp textures/backgrounds/mustard_back.image
svn mv textures/backgrounds/mustard_down.bmp textures/backgrounds/mustard_down.image
svn mv textures/backgrounds/mustard_front.bmp textures/backgrounds/mustard_front.image
svn mv textures/backgrounds/mustard_left.bmp textures/backgrounds/mustard_left.image
svn mv textures/backgrounds/mustard_right.bmp textures/backgrounds/mustard_right.image
svn mv textures/backgrounds/mustard_up.bmp textures/backgrounds/mustard_up.image
svn mv textures/backgrounds/orange_back.bmp textures/backgrounds/orange_back.image
svn mv textures/backgrounds/orange_down.bmp textures/backgrounds/orange_down.image
svn mv textures/backgrounds/orange_front.bmp textures/backgrounds/orange_front.image
svn mv textures/backgrounds/orange_left.bmp textures/backgrounds/orange_left.image
svn mv textures/backgrounds/orange_right.bmp textures/backgrounds/orange_right.image
svn mv textures/backgrounds/orange_up.bmp textures/backgrounds/orange_up.image
svn mv textures/backgrounds/plasma_galaxy_back.bmp textures/backgrounds/plasma_galaxy_back.image
svn mv textures/backgrounds/plasma_galaxy_down.bmp textures/backgrounds/plasma_galaxy_down.image
svn mv textures/backgrounds/plasma_galaxy_front.bmp textures/backgrounds/plasma_galaxy_front.image
svn mv textures/backgrounds/plasma_galaxy_left.bmp textures/backgrounds/plasma_galaxy_left.image
svn mv textures/backgrounds/plasma_galaxy_right.bmp textures/backgrounds/plasma_galaxy_right.image
svn mv textures/backgrounds/plasma_galaxy_up.bmp textures/backgrounds/plasma_galaxy_up.image
svn mv textures/backgrounds/purple2_back.bmp textures/backgrounds/purple2_back.image
svn mv textures/backgrounds/purple2_down.bmp textures/backgrounds/purple2_down.image
svn mv textures/backgrounds/purple2_front.bmp textures/backgrounds/purple2_front.image
svn mv textures/backgrounds/purple2_left.bmp textures/backgrounds/purple2_left.image
svn mv textures/backgrounds/purple2_right.bmp textures/backgrounds/purple2_right.image
svn mv textures/backgrounds/purple2_up.bmp textures/backgrounds/purple2_up.image
svn mv textures/backgrounds/purple_back.bmp textures/backgrounds/purple_back.image
svn mv textures/backgrounds/purple_down.bmp textures/backgrounds/purple_down.image
svn mv textures/backgrounds/purple_front.bmp textures/backgrounds/purple_front.image
svn mv textures/backgrounds/purple_left.bmp textures/backgrounds/purple_left.image
svn mv textures/backgrounds/purple_right.bmp textures/backgrounds/purple_right.image
svn mv textures/backgrounds/purple_up.bmp textures/backgrounds/purple_up.image
svn mv textures/backgrounds/red_back.bmp textures/backgrounds/red_back.image
svn mv textures/backgrounds/red_down.bmp textures/backgrounds/red_down.image
svn mv textures/backgrounds/red_front.bmp textures/backgrounds/red_front.image
svn mv textures/backgrounds/red_left.bmp textures/backgrounds/red_left.image
svn mv textures/backgrounds/red_right.bmp textures/backgrounds/red_right.image
svn mv textures/backgrounds/red_up.bmp textures/backgrounds/red_up.image
svn mv textures/backgrounds/sky_sphere.bmp textures/backgrounds/sky_sphere.image
svn mv textures/backgrounds/somered_back.bmp textures/backgrounds/somered_back.image
svn mv textures/backgrounds/somered_down.bmp textures/backgrounds/somered_down.image
svn mv textures/backgrounds/somered_front.bmp textures/backgrounds/somered_front.image
svn mv textures/backgrounds/somered_left.bmp textures/backgrounds/somered_left.image
svn mv textures/backgrounds/somered_right.bmp textures/backgrounds/somered_right.image
svn mv textures/backgrounds/somered_up.bmp textures/backgrounds/somered_up.image
svn mv textures/backgrounds/verypurple_back.bmp textures/backgrounds/verypurple_back.image
svn mv textures/backgrounds/verypurple_down.bmp textures/backgrounds/verypurple_down.image
svn mv textures/backgrounds/verypurple_front.bmp textures/backgrounds/verypurple_front.image
svn mv textures/backgrounds/verypurple_left.bmp textures/backgrounds/verypurple_left.image
svn mv textures/backgrounds/verypurple_right.bmp textures/backgrounds/verypurple_right.image
svn mv textures/backgrounds/verypurple_up.bmp textures/backgrounds/verypurple_up.image
svn mv textures/backgrounds/white_back.bmp textures/backgrounds/white_back.image
svn mv textures/backgrounds/white_down.bmp textures/backgrounds/white_down.image
svn mv textures/backgrounds/white_front.bmp textures/backgrounds/white_front.image
svn mv textures/backgrounds/white_galaxy_back.bmp textures/backgrounds/white_galaxy_back.image
svn mv textures/backgrounds/white_galaxy_down.bmp textures/backgrounds/white_galaxy_down.image
svn mv textures/backgrounds/white_galaxy_front.bmp textures/backgrounds/white_galaxy_front.image
svn mv textures/backgrounds/white_galaxy_left.bmp textures/backgrounds/white_galaxy_left.image
svn mv textures/backgrounds/white_galaxy_right.bmp textures/backgrounds/white_galaxy_right.image
svn mv textures/backgrounds/white_galaxy_up.bmp textures/backgrounds/white_galaxy_up.image
svn mv textures/backgrounds/white_left.bmp textures/backgrounds/white_left.image
svn mv textures/backgrounds/white_right.bmp textures/backgrounds/white_right.image
svn mv textures/backgrounds/white_up.bmp textures/backgrounds/white_up.image
exit 0
