import Base
import VS
import debug
import dynamic_mission
import vsrandom


tender={"agricultural_rf":("You're the guy who blew up the big green egg, right? I heard the space aliens gave you a super-gun. I wish I had something like that. I'd make me some serious money","I hear the battle against the Kilrathi is heating up. I'm no sympathiser or anything, but I don't think we stand much of a chance.","Some Confeds were walking around here last week. They were asking if anyone knew about some guy called Menesch. I don't think they got much out of the crowd here."),
        "mining_rf":("The situation's real bad for the Confederation. I think they'll have to make some concessions real soon, or else fall to either the Retros or the Kilrathi. I wonder which bases they'll give up first?","I hear the Retro blockades have become almost impossible to break. Some blockades have lasted for weeks. Without adequate supplies, Gemini becomes all the weaker."),
        "pirates_rf":("You look like you've agreed to do a little smuggling. I can tell these things. Be careful, pal. Confeds aren't a big fan of smugglers.","You're a privateer, huh? Good to see you. We've had a shortage of privateer customers lately, since so many are joining up with the Confeds. Drink up!","Pirate activity is on the rise. Without much Confed and Militia presence, pirates have free reign. Don't know that I mind smuggling, actually. I mean, if people want something, why not let them have it?"),
        "oxford_rf":("I hear they're dismantling the Oxford library. That's too bad. I took a holiday in Oxford once. Very pretty place. I wonder why they're going to tear it down","I hope the Retros didn't give you too much trouble on the way here. They're making a lot of people feel like prisoners on their own planets and bases.","I know you! You're that famous singer! Would you do a number for us? It would really make the customers happy. Oh, wait a minute. Wrong guy. Sorry."),
        "military_rf":("You look like you're working for the Confeds. I can tell these things. They're pretty honest guys, but I hear the money's terrible.","Did you hear about the TCS Kinney? The furballs destroyed it in a surprise attack. I bet someone leaked its nav data. Too bad.","Good to see a privateer in here. In tough times like these, the privateers are all out flying around, when they should be in here buying drinks."),
"default":(("Listen, you can't beat New Detroit for great jobs. I mean, it's the Hi-Tech hub of the Gemini sector. Employers who need special services and are willing to pay for them can usually be found there. Check it out.","barspeech/bartenders/listenyoucantbeatnewdetroit.wav"),
             ("I hear there's a real operator hiring out of New Detroit right now. His name's Sandoval. I don't know exactly what he's up to, but with the rumours floating around this guy, he must be up to something big. I hear he's got some kind of valuable art piece he's trying to dump. Probably hot. If you ask me, the guy's a High-Ender, and you should look into getting a piece of his action...","barspeech/bartenders/iheartheresarealoperatorhiring.wav"),
         ("I heard a strange rumor recently. It seems this ship engineer fled the whole way from Sol to Gemini, just because he invented something really big and now the Feds want to catch him. If I were a scientist like him, I would have fled to a safe base next to pirate territory, where no authorities would ever dare disturb me again and keep me from doing my work. Maybe a refinery, since they could provide me with all the tech I'd need for my research. But what can I say, I'm just a bartender."),
         ("Man, those damned Pirates around New Caledonia are really kicking the butts of innocent merchants. It's a hard time to make a good deal as a trader. But a good deal for a Privateer like you. I'd go to that area if I were you."),
         ("I've heard that Azuma Weapons moved their main energy research facility to Auriga, but ship upgrades are rare these days - most companies only sell their stuff to contract partners. That's why I'm working in a bar. Nobody to impress in order to get a box of beer."),
         ("Rumour has it that this guy on Speke is hiring. I heard he's had a spot of trouble with his customers concerning his interpretation of the contraband law. Which is why he is looking for Privateers who aren't afraid of a little heat."),
         ("I have lost contact with an old friend of mine. He's called Melonhead and he has been working as a ship engineer in the Varnus system. I just wonder what has happened to him. I wish I could look up Varnus for myself."),
         ("Looking for a high-paying job? If you can handle yourself in a fight, head to the frontier. I've heard about some guy named Gosshawk in one of Perry's surrounding systems who is helping the Confederation fight the furballs."),
         ("Ever been to Speke in Junction? Man, it's simply amazing what they did with that rubbish pleasure base! The skyline is fantastic. Oh, and rumour has it there's a good job opportunity there for a Privateer like yourself."),
         ("Man, the confed pilots in Gemini are a bunch of lucky guys. I've heard that the Confederation has agreed to build a space hospital near the border. With an institution like that, many lives can be saved and morale will surely experience a boost!"),
         ("I've heard that the people around New Caledonia are quite disappointed with the Militia. Corruption is on the rise, so they are trying to build up a local citizens' Militia on their own. You should go there if you can handle the heat."),
             ("This might sound a little crazy to you, but I've heard there's some guy at New Constantinople, no, make that New Detroit... He's got something that InSys is desperate to get. Something alien. Not Kilrathi. From a civilisation way before them. Before us, even. Worth a mint. If I was a privateer like you, I'd get the hell over there and look into it...","barspeech/bartenders/thismightsoundalittlecrazy.wav"),
             ("Hey, you ever been to New Detroit? Ever hear of a guy named Sandoval? Me and him are tight, but I tell you, lately he's been acting real weird. Heck, we been pals a long time, but I ain't heard stat from him... no one has in weeks. Listen, if you ever dock at New Detroit, be sure to look up Sandoval for me, will you?","barspeech/bartenders/heyyoueverbeentonewdetroit.wav"),
             ("Look, you better steer clear of New Detroit for awhile. Both InSys and the Confed are looking for a guy named Sandoval. He's got into something real big, some kind of alien trouble. Anyway, there's probably a lot of money to be made at New Detroit right now... but if I were you, I'd steer clear. Better poor than dead, eh?","barspeech/bartenders/lookyoubetterstearclearofnewdetroit.wav"),
             ("Did you know that the Troy system is known for moving a lot of Brilliance? I know a lot of privateers turn their noses up at smuggling drugs... but you don't look like the picky type. No offence. Anyway, you'll want to hook up with a woman named Tayla. She's well connected with the underworld there. Tayla can get you the contracts. If she likes you, that is...","barspeech/bartenders/didyouknowthatthetroy.wav"),
             ("You have the look of a smuggler about you. I'm right, am I not? If you have no qualms about running Brilliance, head for the Troy system. I know of a woman there, Tayla, who could use an enterprising young man such as yourself. She mainly channels the merchandise to agricultural and mining worlds, where a little chemical cheer is welcome respite from the tedium. Her routes are well drawn and sparsely patrolled. Good money, low risk...","barspeech/bartenders/youhavethelookofasmuggler.wav"),
             ("Can you keep your mouth shut? There's a group of pirates at Oakham base in Pentonville. These guys move Brilliance in volume. I'm talking bulk here. You could get a piece of that, with the right contact. 'course, if I knew who that was, I'd be running the stuff myself. All I can tell you is, some broad working out of Troy system is their agent...","barspeech/bartenders/canyoukeepyourmouthshut.wav"),
             ("You should've been here an hour ago. Talk about idiots. Some moron calling himself William Riordian was shooting his mouth off about smuggling Brilliance for some knockout named Tayla. He was even blabbing about her having pirate contacts in Pentonville! What a fool. A privateer who can't keep his trap closed about operations is soon unemployed... or dead. Mark my words. He's history.","barspeech/bartenders/youshouldhavebeenherean.wav"),
             ("Here's a tip. Confed patrols around New Constantinople have been kicked up. They're trying to cut back on all the Brilliance that's coming in from Troy. Fat lot of good that'll do. There'll always be privateers like you willing to make the run, and they can't catch them all. They need to crack down on the source. Anyway, the point is, think twice before running Brilliance to New Constantinople. It'll be a tough run, so if you do it, get a damn good price.","barspeech/bartenders/heresatippatrolsaround.wav"),
             ("Looking for work? Who isn't. Well, here's a suggestion, take it or leave it... Ever heard of Roman Lynch? He runs a business empire out of New Constantinople. The guy has his fingers in almost every illegal operation in Gemini... every one worth messing with, that is. He's a hard man, and like all players... he'll screw you over if there's enough profit in it. But even so, there's a lot of money to be made from a guy like that... if you're careful...","barspeech/bartenders/lookingforwork.wav"),
             ("Someone's got to stop these Gemini gangsters. That bastard Roman Lynch sent his trained gorilla in here to bust up my place. Ever seen the guy? His name's Miggs. Lynch uses him as an enforcer. How does he expect me to pay him back if he keeps sending animals to trash my bar? I barely got cleaned up in time to open up this morning! Someday I hope that rich bastard and his lackey get what they deserve!","barspeech/bartenders/someonesgottostopthese.wav"),
             ("This you gotta hear. You know who Roman Lynch is? Only the richest, most-connected crime lord in Gemini Sector. Anyway, word is some nut named Seelig screwed Lynch over on a drug deal big time. Not a good thing to do if you have any plans... like waking up in the morning. It's only a matter of time before Lynch sends some goon to Pentonville to take Seelig out. If I was him, I'd head for Kilrathi space. Believe me, it's safer...","barspeech/bartenders/thisyouvegottohear.wav"),
             ("Man, I tell you, I hate the British. Who doesn't, right? But there's one limey that really pisses me off, privateer named Kroiz. Gun-runner, dangerous as anything, but what really gets me is, he's polite! A pirate who's ready to throw you to the void should at least have the courtesy to be rude, call you a few names, so you know where you stand. Yep, that Kroiz is an English weasel, no doubt about it.","barspeech/bartenders/manihatethebritish.wav"),
             ("Here's a good one. Roman Lynch, Gemini's own Godfather, has family problems. His cousin, Regis, was caught in New Constantinople with a gun in his hand... and a corpse at his feet. Pretty open and shut case. Old Regis is going up on murder charges, and all of Lynch's money can't save the guy. Guess there is some justice, eh buddy?","barspeech/bartenders/heresagoodoneromanlynch.wav"),
             ("I may hear a few rumours now and then, but I'm just a bartender. If you want important information, try Oxford University. I hear they got a library there so big that, if they don't got it, it don't exist.","barspeech/bartenders/imayhearafewrumorsnowand.wav"),
             ("Had a treasure hunter here the other day. You know the type. Seems he'd hit it big on an archaeological dig on a planet in Kilrathi space. Found a prehistoric Kilrathi artefact, proved they sharpened their claws with special tools... something like that. Anyway, he was headed for Oxford, planned on using the library there... try to find out what he had. I say good luck. Oxford's his only hope at this point. If he can't come up with something there, he'll have to research it on Kilrah!","barspeech/bartenders/hadatreasurehunterheretheotherday.wav"),
             ("Boy, I'd hate to be in Hunter Toth's shoes. Have you heard about him? He wrote Prometheus Unplugged. Surely you've read it. That's the book that attacked the Church of Man, remember? He coined the term 'Retros', labelling the faithful as backward for their hatred of technology. Now all those anti-tech freaks are gunning for him, and he's been forced into hiding. Wonderful society we live in, where scholars can be silenced by freaks...","barspeech/bartenders/hehidhatetobeinhuntertoth.wav"),
             ("Looking for the Rhombus crew? No? Too bad. I was told to keep an eye out for some guy who's supposed to hook up with them here. They got a sweet deal going in the Oxford system. Operate out of a ship named Rhombus. They've got the access codes for the Oxford databases. These guys have been robbing the library blind and selling the data. Nice racket, if you can get the codes. Maybe you ought to check it out...","barspeech/bartenders/lookingfortherhombuscrew.wav"),
             ("You look like you've done a little piracy in your time. I happen to know that sometime in the next month or so, Oxford library is going to be receiving a shipment of rare, valuable books... or not receiving it, if someone smart intercepts the freighter. Get it?","barspeech/bartenders/youlooklikeyouvedonealittle.wav"),
             ("Jeez, this weird... guess you'd call it a thing was seen in these parts just days ago. Some kind of ship, gave off an eerie green glow. Must be Kilrathi... though it's sure worse than anything the cats have made so far. This is the same thing that's been destroying capital ships right and left. Tore the TCS Winterrowd to bits without breaking a sweat... though from what I hear, the Winterrowd wasn't all she was cracked up to be...","barspeech/bartenders/jeezthisweird.wav"),
             ("You're not afraid of a tough fight, are you? There's a holdful of credits to be made in the Palan system right now. Bronte Corporation has Palan blockaded right now, trying to block shipments from Rondell, a rival agricultural corporation. Whichever side you work for, expect a lot of trouble... and a lot of credits, friend.","barspeech/bartenders/yourenotafraidofatoughfight.wav"),
             ("You catch the netcast last night? Remember the guy that got that huge Rondell grant? You know, the archaeologist that did those Mars digs... Monkeyhower, something like that... He was digging on Palan when the blockade went up. Hasn't been heard from since. If you ask me, he's a goner. Archaeologists like him, they always have some valuable knick-knack or other. Makes them a target. Count yourself lucky you're not in the relic business, pal. That's one rough trade...","barspeech/bartenders/youcatchthenetcastlastnight.wav"),
             ("There's a lot of talk about the blockade in the Palan system. Supposedly Lemuel Monkhouse is trapped there. I read his book. Drawing on the fossil evidence discovered on Mars and other planets... he believes the entire galaxy was home to an ancient super race. Interesting hypothesis, but I think he's a little carried away. After all, a galaxy-spanning race couldn't just vanish... could it?","barspeech/bartenders/theresalotoftalk.wav"),
             ("There's some money to be made in Rygannon right now. The Exploratory Service is charting an unexplored region in Gemini. Usually this kind of grunt work doesn't pay much... but I hear they've lost a number of ships through jump points out there. They're looking for pilots who can take care of themselves in a scrape. And you look like you fill the bill. Check it out.","barspeech\bartenders\theressomemoneytobemade.wav"),
             ("You remind me of an old friend, name of Garrovick. He worked the Privateer racket, until he signed on with the Exploratory Service. Haven't seen him since, though I heard a nasty rumour that he had disappeared... vanished while charting out of Rygannon. I can't help but think that, whatever got all those Confed ships, took him out as well...","barspeech/bartenders/youremindmeofanoldfriend.wav"),
             ("Myself, I used to fly for the Exploratory Service... 'til I saved up enough to buy this bar. It's a good living. They're not real picky about who they take, and the pay's nothing to sneeze at. If you don't mind getting shot at, from time to time, you oughtta look into it.","barspeech/bartenders/myselfiusedtoflyforthe.wav"),
             ("Have you noticed an increase in Confed patrols lately? Has to do with that killer ship skulking around out there. They're trying like Hell to find it. Funny thing is... instead of hitting military installations, logical Kilrathi targets, it's destroying targets along the usual privateer lanes. Weird, huh?","barspeech/bartenders/haveyounoticedanincrease.wav"),
             ("Friend of mine in the Confed reserves was called into duty last week. His orders were secret, but Hell, he never could keep his mouth shut. Seems there's a Confed fleet massing somewhere in the Gemini sector. Ten to one it's tied into all those random attacks by that marauder vessel. Whatever it is, if it runs into that fleet, it's dead for sure!","barspeech/bartenders/friendofminewascalled.wav"),
             ("Hey, you need to watch your back. Something's up. Admiral Terrell at Perry Naval Base is conducting research on privateering. He's digging for any dirt he can find on privateers operating in the Gemini Sector. Usually all you guys got to worry about is InSys... but now the Confed is getting into the act. Not a good time to get careless. I think he's looking for someone specific, pal. Sure hope your nose is clean... and if it isn't, you better wipe it quick.","barspeech/bartenders/heyyouneedtowatchyourback.wav"),
             ("Have you seen a guy named Tibel Carr?  The InterSys Ops are looking for him.  Something about a murder trial.  I hear that Carr is well connected.  Anyone who can get him off-world wins the jackpot.", "barspeech/bartenders/haveyouseenaguy.wav" ),
             ("I can't stop shaking.  I just heard that the 6th Confederation fleet was lost around Midgard... Gone! The Kilrathi must've destroyed them so fast they couldn't even get a message off! An entire fleet, lost! We're doomed, it's only a matter of time... Drink up, friend. While you still can.","barspeech/bartenders/icantstopshaking.wav")),
        "default_out":(("Sorry, no new info","barspeech/bartenders/sorrynonewinfo.wav"),
                       ("Could you tell me... Excuse me I've got customers, can't talk right now.","barspeech/bartenders/canyoutellme.wav"),
                       ("What's a guy do for fun around here?.........Drink some beer!","barspeech/bartenders/whatsaguydoforfunaroundhere.wav"),
                       ("What's going on around these parts?..........If I hear anything new, you'll be the first to know","barspeech/bartenders/whatsgoingonaroundtheseparts.wav"),
                       ("What's happening on the local scene?..........I can't think of anything now, check back with me later.","barspeech/bartenders/whatshappenningonthelocal.wav"),
                       ("Any local news?..........Quiet!  Can't talk right now, I think we're being watched.","barspeech/bartenders/anylocalnews.wav"),
                       ("Any news I can use?..........Check with me later, after I've talked with some other folks.","barspeech/bartenders/anynewsicanuse.wav"),
                       ("Any news of local interest?..........Sorry man.  I don't have anything for you right now... except for a good Manchester Rum!","barspeech/bartenders/anynewsoflocalinterest.wav"),
                       ("Any good missions out there?..........If you're looking for a mission, talk to the guys who sometimes sit at the front tables there.","barspeech/bartenders/anygoodmissionsoutthere.wav"),
                       ("Any tips for a new kid in town?..........Don't get blown up!  That's all I've got right now.","barspeech/bartenders/anytipsforanewkid.wav")),
        "agricultural":(("I just heard that the 6th Confederation fleet was lost around Midgard... Gone! The Kilrathi must've destroyed them so fast they couldn't even get a message off! An entire fleet, lost! I'm afraid it's only a matter of time... Drink up, friend. While you still can.","barspeech/bartenders/ijustheardthatthe6thconfederationfleet.wav"),
                  ("Friend, you look like a hard man... the kind who looks for dirty work. But this is just an agricultural base. We're farmers, not pirates looking to hire cutthroats and thugs. Please, don't make any trouble here.","barspeech/bartenders/friendyoulooklikeahardman.wav"),
                  ("I hear the Kilrathi are giving the Confed fits. Our boys are spread too thin to protect the outlying colonies, the result being plague and famine for those trapped in the crossfire. The Confed has asked us to up our production of food. It's good for business, but no one here likes profiting from the hardship of others. Anyway, there may be some cargo runs available for you, if you're interested.","barspeech/bartenders/ihearthekilrathiaregivingtheconfedfits.wav"),
                  ("Have you heard the bad news? No one has been able to establish contact with Palan. It's like the whole planet has just... disappeared. I got family there... I... had family there... I think I need a drink.","barspeech/bartenders/haveyouheardthebadnews.wav"),
                  ("Overall, it's been a good year. We've had record crop yields across the board. We think it has something to do with the lessened solar flare activity this year... but what does it matter? We're making out like pirates here for a change.","barspeech/bartenders/overallitsbeenagoodyear.wav")),
        "mining":(("New around here? Good. We could use some more flyboys hauling cargo around here. There's been a shift in demand from the usual metals to radioactive ore. Haven't seen anything like it. With the invention of particle weapons, radioactive ores became less and less valuable. I guess the Confed must be experimenting on some new weapon, huh? Well, the way the war is going, looks like they'll need it.","barspeech/bartenders/newaroundheregood.wav"),
                  ("Just flew in, did you? Let me ask you a question. Did you notice the increased militia and Confed patrols on your approach? The Confed is losing hundreds of ships a day to the war. That means they need more metal for replacement ships, and they're stepping up protection of mining bases to keep raw material out of Kilrathi hands. I don't know about you, but I feel a lot safer because of it...","barspeech/bartenders/justflewindidyou.wav"),
                  ("Hey, an assassin from the Church of Man came by last week. He was looking to whack some artist, a writer or something. Don't ask me what a writer would be doing on a mining base, though. Those Retros give me the creeps. I hear they hate all technology... just the kind of wackos you want to run into on a space station, eh?","barspeech/bartenders/heyanassassinfromthechurch.wav"),
                  ("Welcome to the newest boomtown of the Gemini Sector! We got hold of a dozen of those new Sediment Imaging Satellites, and it's made all the difference in the world. SIS has revealed deposits of tungsten, iron and radioactive ores we never would've found. Business couldn't be better, pal. You came at a good time.","barspeech/bartenders/welcometothenewestboomtown.wav"),
                  ("There is one bit of bad news here. The base is being shaken by tremors. We can't keep the blasted mines from collapsing. We fix one... then a quake hits and collapses two others. Unless this 'roid stabilises, we may be in for some trouble.","barspeech/bartenders/thereisonebitofbadnews.wav"),
                  ("This dancer from Saxtogue came here last week. Real operator, this woman. You heard of Roman Lynch? Well, she lifted one of his bank codes. She's been siphoning off money slow, but I think she's in over her head. If Lynch finds out, she's history.","barspeech/bartenders/thisdancerfromsaxtoguecamehere.wav")),
        "pleasure_out":(("Sorry, no new info","barspeech/bartenders/femsorrynonewinfo.wav"),
                       ("Could you tell me... Excuse me I've got customers, can't talk right now.","barspeech/bartenders/femcanyoutellme.wav"),
                       ("What's a guy do for fun around here?.........Drink some beer!","barspeech/bartenders/femwhatsaguydoforfunaroundhere.wav"),
                       ("What's going on around these parts?..........If I hear anything new, you'll be the first to know","barspeech/bartenders/femwhatsgoingonaroundtheseparts.wav"),
                       ("What's happening on the local scene..........I can't think of anything now, check back with me later.","barspeech/bartenders/femwhatshappenningonthelocal.wav"),
                       ("Any local news..........Think we're being watched.","barspeech/bartenders/femanylocalnews.wav"),
                       ("Any news I can use?..........Check with me later, after I've talked with some other folks.","barspeech/bartenders/femanynewsicanuse.wav"),
                       ("Any news of local interest?..........Sorry man,  I don't have anything for you right now... except a good Manchester Rum!","barspeech/bartenders/femanynewsoflocalinterest.wav"),
                       ("Any good missions out there?..........If you're looking for a mission, talk to the guys who sometimes sit at the front tables there.","barspeech/bartenders/femanygoodmissionsoutthere.wav"),
                       ("Any tips for a new kid in town?..........Don't get blown up!  That's all I've got right now.","barspeech/bartenders/femanytipsforanewkid.wav")),
        "pleasure":(("Get this... the Confed has lost another carrier! I'm afraid it might be related to that Kilrathi secret weapon we've been hearing about. I'm thinking of shutting down the bar awhile, leaving this place... maybe heading deeper into Confed space. The thought of something that nasty creeping around, well, it makes you think, doesn't it?","barspeech/bartenders/femgetthistheconfed.wav"),
                  ("I may hear a few rumours now and then, but I'm just a bartender. If you want important information, try Oxford University. I hear they got a library there so big that, if they don't got it, it don't exist.","barspeech/bartenders/femimayhearafewrumors.wav"),
                  ("Boy, I'd hate to be in Hunter Toth's shoes. Have you heard about him? He wrote Prometheus Unplugged. Surely you've read it. That's the book that attacked the Church of Man, remember? He coined the term 'Retros', labelling the faithful as backward for their hatred of technology. Now all those anti-tech freaks are gunning for him, and he's been forced into hiding. Wonderful society we live in, where scholars can be silenced by freaks...","barspeech/bartenders/femboyidhatetobeinhunter.wav"),
                  ("Blasted Confed hotshots! I hate it when they show up here on leave. You wouldn't believe the ruckus they raised in here. I barely had time to clean up before we opened this morning. And the 17th floor, it's a shambles! These jocks are nuts! Mooning, jumping off balconies into the pool, ballwalking... Listen, take my advice. Avoid the 17th floor. It's not pretty.","barspeech/bartenders/femdamnconfedhotshots.wav"),
                  ("I heard this from a privateer out of Saratov. He ran across this daft bloke while lane skipping along the frontier. The terminal woolly was sitting in the middle of a ship's graveyard, wrecked ships all around. He opens fire on my mate, no reason... ranting and cursing him like he was the devil himself! Fancy that...","barspeech/bartenders/femiheardthisfromaprivateer.wav"),
                  ("Mind, this is just hearsay, but it seems the Kilrathi are all stirred up! The weird thing is, they seem to be looking for something... looking real hard. Who knows what it could be, but whatever it is, it's got them worried. I just hope the activity doesn't scare off our tourists.","barspeech/bartenders/femmindthisisjusthearsay.wav"),
                  ("Did you know that the Troy system is known for moving a lot of Brilliance? I know a lot of privateers turn their noses up at smuggling drugs... but you don't look like the picky type. No offence. Anyway, you'll want to hook up with a woman named Tayla. She's well connected with the underworld there. Tayla can get you the contracts. If she likes you, that is...","barspeech/bartenders/femdidyouknowthatthetroy.wav"),
                  ("Just arrived, have you? Then you haven't heard the latest. Beastly affair. Seems the InterSys Patrols are looking for a murderer. He eliminated a diplomatic party on Matahari. Ten dead. Horrid. I hear this was done to stall negotiations with Oresville, prolonging the labour disputes. What do you think?","barspeech/bartenders/femjustarrivedhaveyou.wav"),
                  ("Friend of mine in the Confed reserves was called into duty last week. His orders were secret, but hey, he never could keep his mouth shut. Seems there's a Confed fleet massing somewhere in the Gemini sector. Ten to one it's tied into all those random attacks by that marauder vessel. Whatever it is, if it runs into that fleet, it's dead for sure!","barspeech/bartenders/femfriendofminewascalled.wav"),
                  ("Had a treasure hunter here the other day. You know the type. Seems he'd hit it big on an archaeological dig on a planet in Kilrathi space. Found a prehistoric Kilrathi artefact, proved they sharpened their claws with special tools... something like that. Anyway, he was headed for Oxford, planned on using the library there... try to find out what he had. I say good luck. Oxford's his only hope at this point. If he can't come up with something there, he'll have to research it on Kilrah!","barspeech/bartenders/femhadatreasurehunterheretheotherday.wav"),
                  ("Here's a tip. Confed patrols around New Constantinople have been kicked up. They're trying to cut back on all the Brilliance that's coming in from Troy. Fat lot of good that'll do. There'll always be privateers like you willing to make the run, and they can't catch them all. They need to crack down on the source. Anyway, the point is, think twice before running Brilliance to New Constantinople. It'll be a tough run, so if you do it, get a real good price.","barspeech/bartenders/femheresatippatrolsaround.wav"),
                  ("I hear there's a real operator hiring out of New Detroit right now. His name's Sandoval. I don't know exactly what he's up to, but with the rumours floating around this guy, he must be up to something big. I hear he's got some kind of valuable art piece he's trying to dump. Probably hot. If you ask me, the guy's a High-Ender, and you should look into getting a piece of his action...","barspeech/bartenders/femiheartheresarealoperator.wav"),
                  ("Jeez, this weird... guess you'd call it a thing was seen in these parts just days ago. Some kind of ship, gave off an eerie green glow. Must be Kilrathi... though it's sure worse than anything the cats have made so far. This is the same thing that's been destroying capital ships right and left. Tore the TCS Winterrowd to bits without breaking a sweat... though from what I hear, the Winterrowd wasn't all she was cracked up to be...","barspeech/bartenders/femjeezthisweird.wav"),
                  ("Listen, you can't beat New Detroit for great jobs. I mean, it's the Hi-Tech hub of the Gemini sector. Employers who need special services and are willing to pay for them can usually be found there. Check it out.","barspeech/bartenders/femlistenyoucantbeatnewdetroit.wav"),
                  ("Looking for the Rhombus crew? No? Too bad. I was told to keep an eye out for some guy who's supposed to hook up with them here. They got a sweet deal going in the Oxford system. Operate out of a ship named Rhombus. They've got the access codes for the Oxford databases. These guys have been robbing the library blind and selling the data. Nice racket, if you can get the codes. Maybe you ought to check it out...","barspeech/bartenders/femlookingfortherhombuscrew.wav"),
                  ("Looking for work? Who isn't. Well, here's a suggestion, take it or leave it... Ever heard of Roman Lynch? He runs a business empire out of New Constantinople. The guy has his fingers in almost every illegal operation in Gemini... every one worth messing with, that is. He's a hard man, and like all players... he'll screw you over if there's enough profit in it. But even so, there's a lot of money to be made from a guy like that... if you're careful...","barspeech/bartenders/femlookingforwork.wav"),
                  ("Someone's got to stop these Gemini gangsters. That bastard Roman Lynch sent his trained gorilla in here to bust up my place. Ever seen the guy? His name's Miggs. Lynch uses him as an enforcer. How does he expect me to pay him back if he keeps sending animals to trash my bar? I barely got cleaned up in time to open up this morning! Someday I hope that rich bastard and his lackey get what they deserve!","barspeech/bartenders/femsomeonesgottostopthese.wav"),
                  ("You look like you've done a little piracy in your time. I happen to know that sometime in the next month or so, Oxford library is going to be receiving a shipment of rare, valuable books... or not receiving it, if someone smart intercepts the freighter. Get it?","barspeech/bartenders/femyoulooklikeyouvedonealittle.wav"),
                  ("Come here for a vacation, have you? You're not alone. Seems like in wartime, everyone has a worse need for entertainment... and that desire for relaxation seems to grow as the war worsens. Anyhow, you did right to come here! We have the finest facilities in the sector. Trust me... would I lie to a guest?","barspeech/bartenders/femcomehereforavacation.wav"),
                  ("Come here for a vacation, have you? You're not alone. Seems like in wartime, everyone has a worse need for entertainment... and that desire for relaxation seems to grow as the war worsens. Anyhow, you did right to come here! We have the finest facilities in the sector. Trust me... would I lie to a guest?","barspeech/bartenders/femcomehereforavacation.wav"),
                  ("You picked a fine time to come to here, sir. With all the bad news about lately, everyone is anxious to find a little getaway... especially the ladies, sir, if you take my meaning. I think you'll find your stay here the best you've ever enjoyed... that is, if you like women... Oh dear... I hope I haven't been too presumptuous...","barspeech/bartenders/femyouvepickedafinetime.wav"),
                  ("You picked a fine time to come to here, sir. With all the bad news about lately, everyone is anxious to find a little getaway... especially the ladies, sir, if you take my meaning. I think you'll find your stay here the best you've ever enjoyed... that is, if you like women... Oh dear... I hope I haven't been too presumptuous...","barspeech/bartenders/femyouvepickedafinetime.wav")),
        "pirates":(("Hey, buddy, you heard the latest? A pirate scoping for business told me this one. Seems the TCS Valiant has just... disappeared. That's the second carrier the Confederation has lost along the border. It's a sure bet the Kilrathi have their paws in this!","barspeech/bartenders/heybuddyhaveyou.wav"),
                  ("Better watch your step, Mister. The... business community here is leery of strangers these days. We've had a lot of problems with undercover Militia agents lately. I'm not saying you're one of 'em, but I'd do my best to look as innocent as possible, if I were you.","barspeech/bartenders/betterwatchyourstepmister.wav"),
#                  "Happy days are here again! You heard? The Confed is slipping in the war effort. Seems the sector is lousy with Kilrathi, and they're giving the Confed fits. Hey, I'm as patriotic as the next guy. I don't want the Confed to give it up, but this means they're diverting their efforts away from law enforcement! That's good news! The less Confed around, the better!",
                  ("Looking for a job? Must be if you're hanging around here. Ever heard of a guy named Roman Lynch? He's a... well, a real mover. Seems he's looking for a wet spesh to whack a guy named Seelig. Lynch runs his empire out of New Constantinople. No thanks, that's what bartenders do. Just remember me when it's time to tip.","barspeech/bartenders/lookingforajobmustbeif.wav"),
                  ("Hey, Mister, have a seat. The first one's on me. No big deal. We're having a boom here, times are good. With all the fighting out along the borders, there's a lot of loot just floating around out there, waiting to be salvaged! Used to be a pirate had to do some shooting to earn his daily bread... nowadays, the only trigger he's gotta pull is wired to a tractor beam!","barspeech/bartenders/heymisterhaveaseatthefirst.wav"),
#                  "I hope you're gonna buy a drink and not just sit here trawling for a job. Business is slow at the bar. People are spending too much time out there on those stressful missions. They need to be in here relaxing, like you. So... what'll it be?",
                  ("Hey, I heard a good one the other day. Seems that there's this hollow asteroid along the Kilrathi border... The thing of it is, the Kilrathi use it as a munitions dump! The guy who finds that dump can help himself to as much ordnance as he can haul!","barspeech/bartenders/heyiheardagoodone.wav"),
#                  "You've got a lot of nerve coming in here looking like that, pal! This joint enforces a strict dress-code. Here, put this eye-patch on before you cause a scene. And ruffle your hair a bit, or someone might think you're with the Navy!",
#                  "If you have a weapon on you, make sure it remains out of sight. The crews of the Skalawag and the Black Death duked it out in here a couple of hours ago, and some people got killed. The last thing we need right now is someone waving his gun around.",
#                  "What are ye pesterin' me for, pal? If you want to be a pirate, you should go talk to the three important-looking pirates in the next room! Wait a second...",
#                  "Kasper Foch, now there's a guy you don't want to mess with. He's the pirate captain that entered an ion storm and flew out again without a scratch, while his three Militia pursuers were never heard of again. Then there's this story going around of how he single-handedly took out a Confed Paradigm, but if ya want my opinion, I think that one's bunk.",
#                  "There's a lot of deserters from the Navy around here these days. Purist and Indep punks they drafted off the street, taught how to fly and then handed a ship. You figure the guys at HQ would be smarter than that.",
#                  "You know, if we lose the war against the Kilrathi, it probably won't matter much, because the majority of us won't be around to see it, but what if we win? The whole fleet would return to peacekeeping duties in human systems, and it would mean the end of space piracy as we know it!",
#                  "Hey, I hope your ship has a large cargo hold. We could always use some more smugglers out there, distributing our goods. Can you believe that there are some colonists out there who still don't know the true glory of Ultimate?",
#                  "This assassin came in here a while ago. Ex-Special Forces guy. Apparently, the government sent some of his collegues to silence him for good after he'd carried out a particularly nasty mission in Kilrathi space, but he made it out and now he'll do any job for money.",
        ),
        "refinery":(("Talk about bizarre stories, this is incredible. A Kilrathi attack force was spotted on sensors. It was moving along the frontier in a search pattern. On Confed screens, one by one, each Kilrathi ship vanished... just vanished... all except one, which moved into Confed space. Strange, huh? Boy, I'm glad I'm here on base, safe and sound. Aren't you?","barspeech/bartenders/talkaboutbizarrestories.wav"),
                  ("Did you hear? A delegation from the Confed Mining Guild swept by here last week. Because of attrition on the front, they're stepping up fighter production, which means more raw ore is being bought, which means it has to be refined, which means everyone is jumping to keep up with the demand. Seems it's gonna be a bad year for the Confed... and a heck of a year for us.","barspeech/bartender/didyouhearadelegationfrom.wav"),
                  ("There's an ugly rumour making the rounds. Heard it from a subcontractor for Confed that they're thinking of militarising our business. They might use the Wartime Emergency Act to take over all mining and refinery operations... which means we'd have to work twice as hard for four times less. I sure hope it ain't true.","barspeech/bartenders/theresanuglyrumor.wav"),
                  ("Heard this from a pirate who left here two days ago. You wouldn't believe the trouble Oxford has been having with data theft. These database jackers I know are looking to trawl the Oxford net. They been at it for months, but it's a tough crack. I bet it's worth it, though. Lot of valuable info at the Oxford Library...","barspeech/bartenders/heardthisfromapiratewholefttwodays.wav"),
                  ("Had a look around yet? Well, you wouldn't guess it from the way things look... but everyone in this place is going to be rich in three years. We just signed a deal with the Merchants' Guild that'll do us right. Because of the quality of our ore, they've waived 75% of the standard Guild cut in exchange for 10% of our gross. Sweet, eh? Bet there's no other refinery that can make that claim...","barspeech/bartenders/hadalookaroundyet.wav"),
                  ("We had another terrorist bombing today. I tell you, it's those damned Mandarins if it's anyone! This war started out to be good business... but if the bombings get much worse, the only profit'll be had by Russo Incorporated... maker of fine red ink everywhere!","barspeech/bartenders/wehadanotherterrorist.wav"),
                  ("Bet you're glad to be here. There's been more trouble from the front. I heard that Confederation Outpost 57 is gone. Now there's a crater on the asteroid where Outpost 57 used to be. Not a trace of residual radiation. No weapon we've ever heard of. Intel reports call it a new Kilrathi weapon. Do you buy that?","barspeech/bartenders/betyourgladtobeheretheres.wav"),
#                  "Sorry for the broken glass on the floor. The base was shook up a bit a couple of hours ago. Apparently, some guy on approach lost control and crashed right into the side of the station. Don't worry, it's nothing our damage control crews can't handle, but the poor guy who crashed won't be flying again. Or breathing, for that matter."
                  ),
        "military":(
                  ("Bet you're glad to be here. There's been more trouble from the front. I heard that Confederation Outpost 57 is gone. Now there's a crater on the asteroid where Outpost 57 used to be. Not a trace of residual radiation. No weapon we've ever heard of. Intel reports call it a new Kilrathi weapon. Do you buy that?","barspeech/bartenders/betyourgladtobeheretheres.wav"),
#                    "A Special Forces unit came through here this morning. Real quiet guys. Looked like they'd seen a lot of action. From what I could gather, they were going to catch a transport out of here and into the fray again later tonight.",
#                    "This Army captain had a drink here yesterday. Tall guy from Mars. Now, I've seen a lot, but this guy... half his face, both of his legs and his left arm had all been replaced with cybernetics due to injuries he'd taken on the field. If it was all with the Mechanist aesthetic, it might have been impressive, but he visually reeked of military hack job. He looked a bit clumsy, it was obvious there hadn't been many nerve endings left to connect to anything.",
#                    "A couple of guys from the Confederate Air Corp were here a while back. We don't get many of those here usually. They may rely on the Navy for transportation between planets, but those Air Corp boys and girls are solid gold when it comes to campaigns planetside!",
#                    "Hey, are you a mercenary? We've got plenty of missions here for you to fly, if you're willing. The fleet is spread thin as it is, so if you want to do your part, you're more than welcome!",
                    ),

        }
for tend in tender:
    if (tend!="default" and tend!="pleasure" and tend.find("_rf")==-1 and tend.find("_out")==-1):
        debug.info("ADDING TENDER " + tend)
        tender[tend]=tender["default"]+tender[tend]

def GetOutOfInfo(str):
   str+="_out"
   if (str in tender):
       return tender[str]
   if ("default_out" in tender):
       return tender["default_out"]
   return ("Sorry, no new info")

speaklimit=2
speaktimes=0

def GetDefaultBartenderText():
    global speaklimit
    global speaktimes
    speaktimes+=1
    if (speaktimes>speaklimit):
        speaklimit=vsrandom.randrange(1,4)
        return GetOutOfInfo("default")
    txt =tender.get("default")
    if (not txt):
        return ("Hello")
    return txt

def GetBartenderText(str):
    global speaklimit
    global speaktimes
    speaktimes+=1
    if (speaktimes>speaklimit):
        return GetOutOfInfo(str)
    txt = tender.get (str)
    rf_campaign_txt=()
    cp=VS.getCurrentPlayer()
    plrun=VS.getPlayerX(cp)
    plr=plrun.isPlayerStarship()

    import quest
    if (quest.getQuestLength(cp,"rf_campaign")):
        tmp=tender.get(str+"_rf")
        if (tmp):
            rf_campaign_txt=tmp
    if (quest.checkSaveValue(cp,"menesch_dead",1.0)):
        rf_campaign_txt=rf_campaign_txt+("Did you hear the news? Governor Menesch is dead! They say he was making deals between the Retros and Kilrathi. Just a little while ago, he got taken out by some privateer. I bet that privateer's got a lot of bounty money coming.","It looks like the Confeds have just about had it here in Gemini. Things are getting way too dangerous. I've already started packing my bags. I wonder where I'll go? Maybe the Magellan sector. I just hope I can find some kind of transportation.")
    if (txt):
        return txt+rf_campaign_txt
    return GetDefaultBartenderText()+rf_campaign_txt

def Drink(turns=100,cost=10):
    """ When you get a drink from the bartender, new dynamic missions are generated. """
    cp=VS.getCurrentPlayer()
    plrun=VS.getPlayerX(cp)
    plr=plrun.isPlayerStarship()
    if (plrun.getCredits() >= cost):
        plrun.addCredits(-cost)
        # dynamic_mission.CreateMissions takes two, not three arguments.
        # I wonder what 'turns' variable was meant to signify?
        #dynamic_mission.CreateMissions(0,6,turns)
        dynamic_mission.CreateMissions(0,6)
        text="Here you go."
    else:
        text="Sorry pal, I don't keep tabs."
    debug.info("DRINK: "+text)
    Base.Message (text)

def Speak(thingstosay):
    (text,sound)=Base.GetRandomBarMessage()
    rndnum=vsrandom.randrange(0,2)
    if (rndnum==1 or text==''):
        mylen=len(thingstosay)
        if (mylen>0):
            x=thingstosay[vsrandom.randrange(0,mylen)]
            if type(x) is tuple or type(x) is list:
                text=str(x[0])
                sound=''
                if len(x)>1:
                    sound=str(x[1])
            else:
                text=str(x)
                sound=''
        else:
            text='Hello!'
            sound=''
    VS.StopAllSounds()
    Base.Message (text)
    if sound and (sound!=''):
        debug.info("playing sound "+str(sound))
        VS.playSound (sound, (0.,0.,0.), (0.,0.,0.))
